[package]
name = "nonlinear"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]

[dependencies]
nalgebra.workspace = true
thiserror.workspace = true
linear = { path = "../linear" }

[dev-dependencies]
approx.workspace = true